server:
  port: 8086

spring:
  application:
    name: cart-service

  datasource:
    url: jdbc:mysql://localhost:3306/cart_db
    username: root
    password: root

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

jwt:
  secret: mysupersecretkeywhichislongenough

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

resilience4j:
  circuitbreaker:
    instances:
      orderServiceCB:
        slidingWindowSize: 10
        failureRateThreshold: 50
        waitDurationInOpenState: 5000ms
        permittedNumberOfCallsInHalfOpenState: 3
        minimumNumberOfCalls: 5
        automaticTransitionFromOpenToHalfOpenEnabled: true
        recordExceptions:
          - java.net.ConnectException
          - java.util.concurrent.TimeoutException
          - feign.FeignException$InternalServerError

management:
  endpoints:
    web:
      exposure:
        include: health,info,circuitbreakers