server:
  port: 8084

spring:
  application:
    name: PAYMENT-SERVICE
  datasource:
    url: jdbc:mysql://localhost:3306/payment_db
    username: root
    password: Govind@1143
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

spring.security:
  user:
    name: admin
    password: admin
