server:
  port: 8082

spring:
  application:
    name: PRODUCT-SERVICE
  datasource:
    url: jdbc:mysql://localhost:3306/product_db
    username: root
    password: Govind@1143
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

spring.security:
  user:
    name: admin
    password: admin
